In [41]:
import torch
from torch.autograd import Variable

# https://blog.csdn.net/Mr_zhuo_/article/details/108132061

x = torch.ones(4)
print("x:", x)

x = Variable(x, requires_grad=True)
print("x.shape:", x.shape)
print("x:", x)
print("--------------------")
y = x**2 + x
print("y:", y)
#梯度参数grad_variables形状必须与Variable一致
grad_variables = torch.FloatTensor([2, 3, 4, 1]) 

y.backward(grad_variables)
#反向传播原理示例：https://blog.csdn.net/deephub/article/details/115438881
print("数值x:", x)
print("x.grade:", x.grad)
print("grad_variables.grade:", grad_variables.grad)
z = 2*x + 1
print("z:", z)

x: tensor([1., 1., 1., 1.])
x.shape: torch.Size([4])
x: tensor([1., 1., 1., 1.], requires_grad=True)
--------------------
y: tensor([2., 2., 2., 2.], grad_fn=<AddBackward0>)
数值x: tensor([1., 1., 1., 1.], requires_grad=True)
x.grade: tensor([ 6.,  9., 12.,  3.])
grad_variables.grade: None
z: tensor([3., 3., 3., 3.], grad_fn=<AddBackward0>)


In [22]:
#自动求导机制
import torch
from torch.autograd import Variable

# 1、简单的求导(求导对象是标量)
x = Variable(torch.Tensor([2]),requires_grad=True)
y = x**2
print(y)
y.backward()
print(x.grad)

tensor([4.], grad_fn=<PowBackward0>)
tensor([4.])


In [28]:
#对矩阵求导
x1 = Variable(torch.randn(10, 20), requires_grad=True)
y1 = Variable(torch.randn(10, 1), requires_grad=True)
W = Variable(torch.randn(20, 1), requires_grad=True)

#matmul表示做矩阵乘法
J = torch.mean(y1 - torch.matmul(x1, W))
J.backward()


print(x1.grad)
print(y1.grad)
print(W.grad)

tensor([[ 0.1311, -0.1033, -0.0323, -0.0786, -0.1015, -0.1312,  0.0653, -0.0382,
          0.0502,  0.0403,  0.0675,  0.1925, -0.0342,  0.0982,  0.1353, -0.0196,
          0.0238, -0.1999, -0.0284,  0.0772],
        [ 0.1311, -0.1033, -0.0323, -0.0786, -0.1015, -0.1312,  0.0653, -0.0382,
          0.0502,  0.0403,  0.0675,  0.1925, -0.0342,  0.0982,  0.1353, -0.0196,
          0.0238, -0.1999, -0.0284,  0.0772],
        [ 0.1311, -0.1033, -0.0323, -0.0786, -0.1015, -0.1312,  0.0653, -0.0382,
          0.0502,  0.0403,  0.0675,  0.1925, -0.0342,  0.0982,  0.1353, -0.0196,
          0.0238, -0.1999, -0.0284,  0.0772],
        [ 0.1311, -0.1033, -0.0323, -0.0786, -0.1015, -0.1312,  0.0653, -0.0382,
          0.0502,  0.0403,  0.0675,  0.1925, -0.0342,  0.0982,  0.1353, -0.0196,
          0.0238, -0.1999, -0.0284,  0.0772],
        [ 0.1311, -0.1033, -0.0323, -0.0786, -0.1015, -0.1312,  0.0653, -0.0382,
          0.0502,  0.0403,  0.0675,  0.1925, -0.0342,  0.0982,  0.1353, -0.0196,
      

In [29]:
#复杂情况的自动求导 多维数组自动求导机制
import torch
from torch.autograd import Variable

x = Variable(torch.FloatTensor([3]),requires_grad=True)
y = x ** 2 + x * 2 + 3
y.backward(retain_graph=True) #保留计算图
print(x.grad)
y.backward()#不保留计算图
print(x.grad) #得到的是第一次求导的值加上第二次求导的值 8 + 8

tensor([8.])
tensor([16.])
