In [4]:
import torch

a = torch.rand(2, 3)
b = torch.rand(2, 3)

print(a)
print(b)

#相乘原理：https://wenku.baidu.com/view/325a0a7d28160b4e767f5acfa1c7aa00b52a9d67.html
y = a*b
print(y.shape)
print(y)

tensor([[0.7440, 0.7503, 0.1469],
        [0.2133, 0.0671, 0.9295]])
tensor([[0.5512, 0.2506, 0.0369],
        [0.5208, 0.4749, 0.1977]])
torch.Size([2, 3])
tensor([[0.4101, 0.1880, 0.0054],
        [0.1111, 0.0319, 0.1837]])
